### ISSUE TITLE
Latest build on Windows in broken 

### ISSUE THREAD

**Issue by adam-urbanczyk** [conda-forge/freeimage-feedstock#25]
The package win-64/freeimage-3.18.0-hd5a7501_6.tar.bz2  contains no DLL files. And in the build log you actually see this:

```
CMake Error at D:/bld/freeimage_1615795805936/work/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (set):
  Syntax error in cmake code at

    D:/bld/freeimage_1615795805936/work/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2

  when parsing string

    D:\a\1\s\recipe/cmake;${CMAKE_MODULE_PATH}

  Invalid character escape '\a'.


CMake Error at D:/bld/freeimage_1615795805936/_build_env/Library/share/cmake-3.19/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  D:/bld/freeimage_1615795805936/_build_env/Library/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by wolfv** [comment]
Thanks for noticing! I will move the package to broken.

**Comment by traversaro** [comment]
Interesting, the build in the PR ~https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=290371&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f went fine~ actually also there the build failed but the CI was green, not sure what was happening, while the after-merge build was failing https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=290377&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f, but the package was uploaded in any case.

**Comment by wolfv** [comment]
https://github.com/conda-forge/admin-requests/pull/245

do we have tests checking for file existence? 
We might need to add some `if errorlevel exit 1`

**Comment by adam-urbanczyk** [comment]
It was "fake" green: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=290377&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=488

You will be indeed better off with `if errorlevel exit 1`

**Comment by traversaro** [comment]
I am adding some checks in https://github.com/conda-forge/freeimage-feedstock/pull/26 .

**Comment by wolfv** [comment]
thanks @traversaro !

**Comment by wolfv** [comment]
@adam-urbanczyk if you could try again? Hopefully the latest build of freeimage is fine.

**Comment by adam-urbanczyk** [comment]
It is working now, thanks!
