### ISSUE TITLE
Add run_exports and Windows support 

### ISSUE THREAD

**Issue by wolfv** [conda-forge/freeimage-feedstock#7]
Hi, one of the libraries I need also needs freeimage. 

Now, this recipe doesn't seem to support run_exports yet, right? I think at least that should be added. 

Also on `vcpkg` we can find a pretty good looking CMakeLists for this project, as well as a bunch of patches: https://github.com/microsoft/vcpkg/tree/master/ports/freeimage
This looks pretty nice to me. I think it would also give Windows support for free (which I would appreciate).

What do you think?

**Comment by almarklein** [comment]
Sounds good. Is this something you'd have a look at? I cannot devote much time on this myself.
