### ISSUE TITLE
osx: missing libfreeimage.dynlib

### ISSUE THREAD

**Issue by looooo** [conda-forge/freeimage-feedstock#9]
Error for freecad-feedstock:
```
ninja: error: '/usr/local/miniconda/conda-bld/freecad_1570957681082/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libfreeimage.dylib', needed by 'Mod/Import/Import.so', missing and no known rule to make it
```

in version 3.17.0
`libfreeimage.dylib`

in version 3.18.0:
`libfreeimage.3.dylib`

**Comment by looooo** [comment]
@conda-forge/core do we need to pin freeimage? There seems to be no issues for windows and linux.

**Comment by CJ-Wright** [comment]
Can you open a pinning PR with a migration? See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/271/files#diff-75576eba2a574dd4bce625fa345716b9 for how to add a package to the pins

**Comment by looooo** [comment]
I am not yet sure if pinning is necessary as the versions should be compatible.

**Comment by mariusvniekerk** [comment]
Should we make this recipe generate a symlink?

**Comment by looooo** [comment]
yes, I think we should do so. For linux there is already a symlink.

**Comment by looooo** [comment]
Btw.: I removed the freeimage dependency of occt-feedstock, so this is not a problem for me anymore.

**Comment by wolfv** [comment]
we are building freeimage with cmake now so this issue is luckily gone.
